[package]
name = "lntrn-lockscreen"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "lntrn-lockscreen"
path = "src/main.rs"

[dependencies]
anyhow = "1"
lntrn-render = { path = "../lntrn-render" }
lntrn-theme = { path = "../lntrn-theme" }
raw-window-handle = "0.6"
wayland-backend = { version = "0.3", features = ["client_system"] }
wayland-client = "0.31"
wayland-protocols = { version = "0.32", features = ["client", "staging", "unstable"] }
wgpu = "28"
xkbcommon = "0.9"
image = { version = "0.25", default-features = false, features = ["png"] }
pam-client = "0.5"
libc = "0.2"
