[package]
name = "lntrn-system-settings"
version = "0.2.0"
description = "Lantern DE - System Settings, on Lantern UI 2"
authors = ["Alva"]
edition = "2024"

[[bin]]
name = "lntrn-system-settings"
path = "src/main.rs"

[dependencies]
lntrn-app = { path = "../../lantern-ui-2/crates/lntrn-app" }
lntrn-ui = { path = "../../lantern-ui-2/crates/lntrn-ui" }
lntrn-core = { path = "../../lantern-ui-2/crates/lntrn-core" }
lntrn-math = { path = "../../lantern-ui-2/crates/lntrn-math" }
lntrn-props = { path = "../../lantern-ui-2/crates/lntrn-props" }
lntrn-data = { path = "../../lantern-ui-2/crates/lntrn-data" }
lntrn-sys = { path = "../../lantern-ui-2/crates/lntrn-sys" }
lntrn-svg = { path = "../../lantern-ui-2/crates/lntrn-svg" }
lntrn-image = { path = "../../lantern-ui-2/crates/lntrn-image" }
lntrn-icons = { path = "../lntrn-icons" }
lntrn-kit = { path = "../lntrn-kit" }
