//! Generates the override stylesheet injected into Spotify.
//!
//! Spotify's UI is the "encore" web design system. Components reference a set
//! of CSS custom properties (`--background-base`, `--essential-bright-accent`,
//! …). We override those on `:root` / the themed scope so the whole app picks
//! up Lantern's [`FoxPalette`] — then knock the chrome backgrounds translucent
//! so the compositor's blur shows through.

use lntrn_theme::{config, Rgba, ThemeVariant};

/// Marker so we can find + strip our own injected block on re-apply.
pub const MARKER_ID: &str = "lntrn-spotify-theme";

/// Resolved knobs for one theme generation.
pub struct ThemeInputs {
    pub variant: ThemeVariant,
    pub accent: Rgba,
    /// Alpha for the deepest background layer (lets blur through). 0.0–1.0.
    pub base_alpha: f32,
    /// Alpha for elevated surfaces / panels (kept higher for readability).
    pub surface_alpha: f32,
    /// Inject a `font-family` override using the Lantern proportional font.
    pub override_font: bool,
}

impl ThemeInputs {
    /// Pull everything from the live `lantern.toml`, with overridable alphas.
    pub fn from_config(base_alpha: Option<f32>, surface_alpha: Option<f32>) -> ThemeInputs {
        let variant = config::active_variant();
        let accent = config::active_accent().unwrap_or_else(|| variant.accent());
        // Default base transparency follows the DE's window opacity so Spotify
        // matches the rest of the desktop; surfaces get a readable floor.
        let cfg_op = config::background_opacity().clamp(0.0, 1.0);
        let base = base_alpha.unwrap_or(cfg_op).clamp(0.0, 1.0);
        let surf = surface_alpha.unwrap_or(cfg_op.max(0.62)).clamp(0.0, 1.0);
        ThemeInputs {
            variant,
            accent,
            base_alpha: base,
            surface_alpha: surf,
            override_font: true,
        }
    }
}

/// A deliberately unmistakable stylesheet to confirm our CSS is actually
/// loaded by Spotify: hue-rotates the whole app (green → magenta) and draws a
/// fat magenta border around the window. If you see this, the pipeline works.
pub fn generate_loud() -> String {
    "/* LNTRN LOUD DIAGNOSTIC — if you see hue-shifted colors + a magenta \
     border, injection works. */\n\
     html{filter:hue-rotate(150deg) saturate(1.5)!important}\n\
     body{border:10px solid #ff00ff!important;box-sizing:border-box!important}\n"
        .to_string()
}

/// Build the full inner CSS for the given inputs.
pub fn generate(inp: &ThemeInputs) -> String {
    let p = inp.variant.palette();
    // Prefer the user's configured background color when set.
    let bg = config::active_background_color().unwrap_or(p.bg);
    let surface = p.surface;
    let surface2 = p.surface_2;
    let sidebar = p.sidebar;
    let accent = inp.accent;
    let text = p.text;
    let text2 = p.text_secondary;
    let muted = p.muted;

    let base_a = inp.base_alpha;
    let surf_a = inp.surface_alpha;

    let mut css = String::new();
    css.push_str("/* Generated by lntrn-spotify-theme — do not edit by hand. */\n");

    // ── Design-token overrides (the bulk of the recolor) ──
    css.push_str(":root,.encore-dark-theme,.encore-light-theme,html{\n");
    line(&mut css, "--background-base", &rgba(bg, base_a));
    line(
        &mut css,
        "--background-highlight",
        &rgba(surface, (base_a + 0.08).min(1.0)),
    );
    line(
        &mut css,
        "--background-press",
        &rgba(surface2, (base_a + 0.12).min(1.0)),
    );
    line(
        &mut css,
        "--background-elevated-base",
        &rgba(surface, surf_a),
    );
    line(
        &mut css,
        "--background-elevated-highlight",
        &rgba(surface2, surf_a),
    );
    line(
        &mut css,
        "--background-elevated-press",
        &rgba(surface2, surf_a),
    );
    line(&mut css, "--background-tinted-base", &rgba(text, 0.07));
    line(&mut css, "--background-tinted-highlight", &rgba(text, 0.10));
    line(&mut css, "--background-tinted-press", &rgba(text, 0.14));
    line(&mut css, "--text-base", &rgb(text));
    line(&mut css, "--text-subdued", &rgb(text2));
    line(&mut css, "--text-bright-accent", &rgb(accent));
    line(&mut css, "--essential-base", &rgb(text));
    line(&mut css, "--essential-subdued", &rgb(muted));
    line(&mut css, "--essential-bright-accent", &rgb(accent));
    line(&mut css, "--background-bright-accent", &rgb(accent));
    line(&mut css, "--decorative-base", &rgb(surface2));
    line(&mut css, "--decorative-subdued", &rgb(muted));
    css.push_str("}\n");

    // ── Let the compositor blur show through the app chrome ──
    css.push_str(concat!(
        "html,body,#main,.Root__top-container,.Root__main-view,",
        ".main-view-container,.main-view-container__scroll-node,",
        ".Root__globalNav,.global-nav,.main-gridContainer-gridContainer{",
        "background:transparent!important;background-color:transparent!important}\n"
    ));

    // ── Keep panels readable over the blur ──
    let panel = rgba(surface, surf_a);
    let nav = rgba(sidebar, surf_a);
    css.push_str(".Root__nav-bar,.main-yourLibraryX-libraryContainer,");
    css.push_str(".main-yourLibrary-libraryContainer{background-color:");
    css.push_str(&nav);
    css.push_str("!important}\n");
    css.push_str(".Root__now-playing-bar,.main-nowPlayingBar-container,");
    css.push_str(".Root__right-sidebar,.main-buddyFeed-container{background-color:");
    css.push_str(&panel);
    css.push_str("!important}\n");

    // ── Accent touches: links, selection, scrollbar ──
    css.push_str("a{color:");
    css.push_str(&rgb(accent));
    css.push_str("}\n::selection{background:");
    css.push_str(&rgba(accent, 0.45));
    css.push_str("}\n");
    css.push_str("::-webkit-scrollbar-thumb{background-color:");
    css.push_str(&rgba(text, 0.28));
    css.push_str("!important;border-radius:6px}\n");

    // ── Optional font swap to the Lantern proportional family ──
    if inp.override_font {
        css.push_str("body,button,input,.encore-text{font-family:\"");
        css.push_str(lntrn_theme::FAMILY_PROPORTIONAL);
        css.push_str("\",'Spotify Mix','SpotifyMixUI',sans-serif!important}\n");
    }

    css
}

fn line(out: &mut String, var: &str, value: &str) {
    out.push_str(var);
    out.push(':');
    out.push_str(value);
    out.push_str("!important;\n");
}

fn rgb(c: Rgba) -> String {
    format!("rgb({},{},{})", c.r, c.g, c.b)
}

/// `alpha` is multiplied with the color's own alpha so palette entries that
/// are already translucent (e.g. Night Sky surfaces) stay that way.
fn rgba(c: Rgba, alpha: f32) -> String {
    let a = (alpha * (c.a as f32 / 255.0)).clamp(0.0, 1.0);
    format!("rgba({},{},{},{:.3})", c.r, c.g, c.b, a)
}
