[package]
name = "lntrn-screenshot"
version = "0.1.0"
description = "Screenshot tool for Lantern DE"
authors = ["Jca56"]
edition = "2021"

[dependencies]
anyhow = "1"
image = { version = "0.25", default-features = false, features = ["png"] }
libc = "0.2"
lntrn-render = { path = "../lntrn-render" }
raw-window-handle = "0.6"
wayland-backend = { version = "0.3", features = ["client_system"] }
wayland-client = "0.31"
wayland-protocols = { version = "0.32", features = ["client"] }
wayland-protocols-wlr = { version = "0.3", features = ["client"] }
wgpu = "28"
