[package]
name = "lntrn-screencopy"
version = "0.1.0"
description = "Screen recorder for Lantern DE"
edition = "2021"

[dependencies]
anyhow = "1"
libc = "0.2"
lntrn-render = { path = "../lntrn-render" }
raw-window-handle = "0.6"
wayland-backend = { version = "0.3", features = ["client_system"] }
wayland-client = "0.31"
wayland-protocols = { version = "0.32", features = ["client"] }
wayland-protocols-wlr = { version = "0.3", features = ["client"] }
wgpu = "28"
